name: handy_hub
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  internet_speed_test: ^1.5.0
  translator: ^1.0.3+1
  flutter_compass: ^0.7.0
  sensors_plus: ^6.1.1
  flutter_local_notifications: ^12.0.0
  intl: ^0.20.2
  pdf: ^3.6.0  # PDF generation library
  printing: ^5.6.0 
  image_picker: ^0.8.5+3
  html: ^0.15.0
  docx_to_text: ^1.0.1
  path_provider: ^2.1.2
  image: ^4.1.7
  file_picker: ^9.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_internet_speed_test: ^1.5.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your assets here

  # Add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# Add flutter_launcher_icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.jpg"  # Path to your icon image
